#!/bin/bash
export KUBECONFIG=~/.kube/current
KCONTEXT=$(kubectl config current-context 2>/dev/null)
if [[ $?=="0" ]]; then
    CC=$(kubectl config view -ojsonpath='{..current-context}')
    KNAMESPACE=$(kubectl config view -ojsonpath="{.Contexts[?(@.Name==\"$CC\")]..namespace}")
    echo "☸ $KCONTEXT/$KNAMESPACE ☸"
    echo "☸ $KCONTEXT/$KNAMESPACE ☸"
    if [ "$KCONTEXT" == "minikube" ]; then
      echo \#4040FF
      exit
    fi
    echo \#FF00FF
fi
