#!/usr/bin/env bash
set -euo pipefail
# it's all day until 7pm then it's night mode
statusfile=/tmp/night-mode-status
if [ ! -f "$statusfile" ]; then
  echo "0" > $statusfile
fi
current=$(cat $statusfile)

night_mode() { 
  for disp in $(xrandr |  awk '$2 ~ /^connected/ && $3 ~ /x/ || $3 ~ /primary/ {print $1}'); do
    xrandr --output "$disp" --gamma "$1" --brightness "$2"
  done
}


night() {
  night_mode 1:1:0.5 0.7
  echo "🌙"
}

day() {
  night_mode 1:1:1 1.0
  echo "🌞"
}


toggle() {
  if [[ "$current" == "0" ]]; then
    echo "1" > "$statusfile"
    day
    return
  fi
  echo "0" > "$statusfile"
  night
}

if [ ! -z "$BLOCK_BUTTON" ];
then
  toggle
  exit
fi

H=$(date +%H)
if (( 8 <= 10#$H && 10#$H < 19 )); then
  day
  exit
fi

night


