#!/usr/bin/env php
<?php

/**
 * i3blocks Battery status
 * This script perform a battery status check and prints
 * the percentage along with the proper icon.
 * If the AC is online a plug icon is displayed
 *
 * Configuration Example
 *
 * [power]
 * markup=pango
 * instance=BAT0,AC0
 * command=$HOME/.dotfiles/scripts/battery
 * interval=5
 * align=center
 *
 * Copyright (C) 2016 Lorenzo Fontana <fontanalorenz@gmail.com>
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
function getBatteryIcon($charge)
{
    $icons = [
        0 => '  ',
        20 => '  ',
        50 => '  ',
        75 => '  ',
        100 => '  ',
    ];

    return array_reduce(array_keys($icons), function($carry, $value) use ($icons, $charge) {
        if ($value <= $charge) {
            return $icons[$value];
        }
        return $carry;
    });
}

$default = ['BAT0', 'AC0'];
$instances = getenv('BLOCK_INSTANCE') ? explode(',', getenv('BLOCK_INSTANCE')) : $default;
$instances = count($instances) < 2 ? $instances : $default;

$now = file_get_contents(sprintf("/sys/class/power_supply/%s/energy_now", $instances[0]));
$full = file_get_contents(sprintf("/sys/class/power_supply/%s/energy_full", $instances[0]));
$acOnline = (bool)trim(file_get_contents(sprintf("/sys/class/power_supply/%s/online", $instances[1])));

$charge = number_format($now / $full * 100, 2);

$lowCharge = $charge < 20;

$powerSourceIcon = $acOnline ? ' ' : getBatteryIcon($charge);

echo sprintf("%s %s", $powerSourceIcon, $charge) . PHP_EOL;

if ($lowCharge) {
    exit(33);
}
