#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: docker-ip CONTAINER"
    echo ""
    echo "Gets the IP address of the specified docker container"
else

docker inspect --format '{{ .NetworkSettings.IPAddress }}' $1

fi
