#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: docker-php CONTAINER SCRIPT"
    echo ""
    echo "Executes the given php script into the docker container."
    echo "      -d      Xdebug session"
    exit
fi

if [ $1 = "-d" ]; then
    docker exec -i $2 bash -c "export XDEBUG_CONFIG='remote_enable=1 idekey=LOCALDEBUGGER remote_host=172.17.42.1 remote_port=9000' && php ${*:3}"
else
    docker exec -i $1 php "${*:2}"
fi
